name: Ubuntu SSH Virtual Machine

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Prepare system
        run: sudo apt-get update

      - name: Start SSH session
        run: |
          bash linux-run.sh \
            "${{ secrets.LINUX_USER_PASSWORD }}" \
            "${{ secrets.NGROK_AUTH_TOKEN }}" \
            "${{ secrets.LINUX_USERNAME }}" \
            "${{ secrets.LINUX_MACHINE_NAME }}"

      - name: Keep runner alive
        run: sleep 6h
